### ISSUE TITLE
Generate directories for back catalogue

### ISSUE THREAD

**Issue by blakemerryman** [NashvilleCocoaHeads/Presentation-Archive#3]
Need to run the `generate_folders_for_year` script for however many years of back catalogue we want to support.

Example usage:
```
>: swift generate_folders_for_year.swift --year 2017
```

**Comment by addisonwebb** [comment]
I have talks from 2016 and 2017. Do you think there is any benefit to going further back than 2016?

**Comment by blakemerryman** [comment]
Let's just go back to 2016 for now. If we have people show interest in going further back, we'll address then.

**Comment by blakemerryman** [comment]
Addressed by https://github.com/NashvilleCocoaHeads/Presentation-Archive/pull/5
