### ISSUE TITLE
Update README format

### ISSUE THREAD

**Issue by addisonwebb** [NashvilleCocoaHeads/Presentation-Archive#6]
I think it would be easier to read if we added some formatting to the different sections of the README. Below is an example of what I am thinking.

### Current README template:
```
# Nashville CocoaHeads Presentation for ${MONTH} ${YEAR}

Topic:

Description:

Presenter:

Bio:
```

### Proposed README template:
```
# Nashville CocoaHeads Presentation for ${MONTH} ${YEAR}

### Topic:

### Description:

### Presenter:

### Bio:
```

### Example:

```
# Nashville CocoaHeads Presentation for February 2016

### Topic:
Introduction to CloudKit

### Description:
This month, Addison Webb will be presenting on Apple's CloudKit (https://developer.apple.com/icloud/). With the recent announcement that Parse is shutting down, CloudKit offers a viable alternative to power the backend of your application.

### Presenter:
[Addison Webb](https://twitter.com/addisonwebb)

### Bio:
You can find Addison on Github (https://github.com/addisonwebb) and Twitter (https://twitter.com/addisonwebb).
```

# Nashville CocoaHeads Presentation for February 2016

### Topic:
Introduction to CloudKit

### Description:
This month, Addison Webb will be presenting on Apple's CloudKit (https://developer.apple.com/icloud/). With the recent announcement that Parse is shutting down, CloudKit offers a viable alternative to power the backend of your application.

### Presenter:
[Addison Webb](https://twitter.com/addisonwebb)

### Bio:
You can find Addison on Github (https://github.com/addisonwebb) and Twitter (https://twitter.com/addisonwebb).

**Comment by blakemerryman** [comment]
@addisonwebb I think this is a great suggestion. See https://github.com/NashvilleCocoaHeads/Presentation-Archive/pull/7
